/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Collaborators: typeof import('./src/components/Collaborators.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Members: typeof import('./src/components/Members.vue')['default']
    Milestones: typeof import('./src/components/Milestones.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
